var shuffleSequence = seq("intro", "info", "practice", sepWith("sep", not("sep")), "contact", "sr", "code");

var ds = "RegionedSentence";
var qs = "Question";

var manualSendResults = true;

var defaults = [
	"Separator", {
		transfer: 1500,
		normalMessage: "Please wait for the next sentence",
		errorMessage: "Wrong. Please wait for the next sentence" },
	"RegionedSentence", {
		mode: "self-paced reading" },
	"Question", {
		as: ["Yes","No"],
		randomOrder: false,
		hasCorrect: true }
];

var items = [
    ["sr", "__SendResults__", { }],
	["sep", "Separator", {}],
	["intro", "Message", {consentRequired: true, html: {include: "intro.html"}}],
	["info", "Form", {html: {include: "info.html"}}],
	[["defaultStim",[1,1]], ds, {s: "I do the easy stuff now. "}],
	[["defaultStim",[1,2]], ds, {s: "I do the easy stuff now. "}],
	[["defaultStim",[2,1]], ds, {s: "But I am trying to work up to three miles. "}],
	[["defaultStim",[2,2]], ds, {s: "But I am trying to work up to three miles. "}],
	[["defaultStim",[3,1]], ds, {s: "There is a thing called Pfeiffer Rim. "}, 
		qs, {q: "Is there something called Pfeiffer Rim?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[3,1]], ds, {s: "There is a thing called Pfeiffer Rim. "}, 
		qs, {q: "Is there something called Pfeiffer Rim?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[4,1]], ds, {s: "Well, they started out really bad."}, 
		qs, {q: "Did they start out really bad?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[4,1]], ds, {s: "Well, they started out really bad."}, 
		qs, {q: "Did they start out really bad?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[5,1]], ds, {s: "They would have collapsed. "}],
	[["defaultStim",[5,2]], ds, {s: "They would have collapsed. "}],
	[["defaultStim",[6,1]], ds, {s: "I was working in Cameroon, Africa. "}, 
		qs, {q: "Is Cameroon in Africa?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[6,1]], ds, {s: "I was working in Cameroon, Africa. "}, 
		qs, {q: "Is Cameroon in Africa?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[7,1]], ds, {s: "We have a set amount."}, 
		qs, {q: "Is there a variable amount?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[7,1]], ds, {s: "We have a set amount."}, 
		qs, {q: "Is there a variable amount?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[8,1]], ds, {s: "Well, they are dangerous. "}],
	[["defaultStim",[8,2]], ds, {s: "Well, they are dangerous. "}],
	[["defaultStim",[9,1]], ds, {s: "You clip recipes."}, 
		qs, {q: "Can recipes be clipped?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[9,1]], ds, {s: "You clip recipes."}, 
		qs, {q: "Can recipes be clipped?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[10,1]], ds, {s: "But all of a sudden it just was not working. "}],
	[["defaultStim",[10,2]], ds, {s: "But all of a sudden it just was not working. "}],
	[["defaultStim",[11,1]], ds, {s: "Well, my wife is from Galveston. "}],
	[["defaultStim",[11,2]], ds, {s: "Well, my wife is from Galveston. "}],
	[["defaultStim",[12,1]], ds, {s: "I work in the computer lab at school. "}, 
		qs, {q: "Are there computer labs in some schools?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[12,1]], ds, {s: "I work in the computer lab at school. "}, 
		qs, {q: "Are there computer labs in some schools?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[13,1]], ds, {s: "Recycled paper is actually very expensive. "}, 
		qs, {q: "Is recycled paper cheap?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[13,1]], ds, {s: "Recycled paper is actually very expensive. "}, 
		qs, {q: "Is recycled paper cheap?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[14,1]], ds, {s: "That is always good."}],
	[["defaultStim",[14,2]], ds, {s: "That is always good."}],
	[["defaultStim",[15,1]], ds, {s: "But, we went that way."}],
	[["defaultStim",[15,2]], ds, {s: "But, we went that way."}],
	[["defaultStim",[16,1]], ds, {s: "He has gotten out."}],
	[["defaultStim",[16,2]], ds, {s: "He has gotten out."}],
	[["defaultStim",[17,1]], ds, {s: "Two ways was seventy miles."}, 
		qs, {q: "Was it a seventy mile travel for two ways?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[17,1]], ds, {s: "Two ways was seventy miles."}, 
		qs, {q: "Was it a seventy mile travel for two ways?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[18,1]], ds, {s: "With all of you living so close together. "}],
	[["defaultStim",[18,2]], ds, {s: "With all of you living so close together. "}],
	[["defaultStim",[19,1]], ds, {s: "But you actually hand quilted it yourself. "}, 
		qs, {q: "Is it possible to quilt by hand?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[19,1]], ds, {s: "But you actually hand quilted it yourself. "}, 
		qs, {q: "Is it possible to quilt by hand?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[20,1]], ds, {s: "Oh, in the oil business. "}],
	[["defaultStim",[20,2]], ds, {s: "Oh, in the oil business. "}],
	[["defaultStim",[21,1]], ds, {s: "And it is so easy. "}],
	[["defaultStim",[21,2]], ds, {s: "And it is so easy. "}],
	[["defaultStim",[22,1]], ds, {s: " I hope I do not see a lot more single moms."}, 
		qs, {q: "Is the abundance of single moms a good sign?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[22,1]], ds, {s: " I hope I do not see a lot more single moms."}, 
		qs, {q: "Is the abundance of single moms a good sign?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[23,1]], ds, {s: "So it was like I had to go all the way back to the main drain and start all over. "}, 
		qs, {q: "Was it necessary to start over again?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[23,1]], ds, {s: "So it was like I had to go all the way back to the main drain and start all over. "}, 
		qs, {q: "Was it necessary to start over again?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[24,1]], ds, {s: "And when you are writing up budgets, you wonder, okay, how much money do we need?"}],
	[["defaultStim",[24,1]], ds, {s: "And when you are writing up budgets, you wonder, okay, how much money do we need?"}, 
		qs, {q: "When writing budgets, is the amount of money needed already known? " , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[25,1]], ds, {s: "Well I know how you feel. "}, 
		qs, {q: "When writing budgets, is the amount of money needed already known? " , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[25,2]], ds, {s: "Well I know how you feel. "}],
	[["defaultStim",[26,1]], ds, {s: "Now we can put all our yard clippings out. "}, 
		qs, {q: "Do the yard clippings go out?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[26,1]], ds, {s: "Now we can put all our yard clippings out. "}, 
		qs, {q: "Do the yard clippings go out?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[27,1]], ds, {s: "But I have been unable to do that, because I hurt my foot about five years ago. "}, 
		qs, {q: "Can all activities be done with a hurt foot?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[27,1]], ds, {s: "But I have been unable to do that, because I hurt my foot about five years ago. "}, 
		qs, {q: "Can all activities be done with a hurt foot?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[28,1]], ds, {s: "Maybe it is not drywall. "}],
	[["defaultStim",[28,2]], ds, {s: "Maybe it is not drywall. "}],
	[["defaultStim",[29,1]], ds, {s: "Maybe this pre-group of people could decide where they could go from there. "}, 
		qs, {q: "Did the pre-group of people know where to go from there?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[29,1]], ds, {s: "Maybe this pre-group of people could decide where they could go from there. "}, 
		qs, {q: "Did the pre-group of people know where to go from there?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[30,1]], ds, {s: "We are late twenties. "}],
	[["defaultStim",[30,2]], ds, {s: "We are late twenties. "}],
	[["defaultStim",[31,1]], ds, {s: "Well, it was nice talking to you. "}],
	[["defaultStim",[31,2]], ds, {s: "Well, it was nice talking to you. "}],
	[["defaultStim",[32,1]], ds, {s: "Oh, would it not though? "}],
	[["defaultStim",[32,2]], ds, {s: "Oh, would it not though? "}],
	[["defaultStim",[33,1]], ds, {s: "We kind of give her the third degree. "}],
	[["defaultStim",[33,2]], ds, {s: "We kind of give her the third degree. "}],
	[["defaultStim",[34,1]], ds, {s: "And that was pretty scandalous. "}],
	[["defaultStim",[34,2]], ds, {s: "And that was pretty scandalous. "}],
	[["defaultStim",[35,1]], ds, {s: "Ours is on the small end."}],
	[["defaultStim",[35,2]], ds, {s: "Ours is on the small end."}],
	[["defaultStim",[36,1]], ds, {s: " I could easily envision that. "}],
	[["defaultStim",[36,2]], ds, {s: " I could easily envision that. "}],
	[["defaultStim",[37,1]], ds, {s: "We have very windy winters and very cold. "}, 
		qs, {q: "Are the winters warm?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[37,1]], ds, {s: "We have very windy winters and very cold. "}, 
		qs, {q: "Are the winters warm?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[38,1]], ds, {s: "So we still feel very new."}],
	[["defaultStim",[38,2]], ds, {s: "So we still feel very new."}],
	[["defaultStim",[39,1]], ds, {s: "It was really amazing. "}],
	[["defaultStim",[39,2]], ds, {s: "It was really amazing. "}],
	[["defaultStim",[40,1]], ds, {s: "And then they said okay."}],
	[["defaultStim",[40,2]], ds, {s: "And then they said okay."}],
	[["defaultStim",[41,1]], ds, {s: "And then he just started doing it. "}],
	[["defaultStim",[41,2]], ds, {s: "And then he just started doing it. "}],
	[["defaultStim",[42,1]], ds, {s: "And there is just no time. "}, 
		qs, {q: "Is there a lot of time?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[42,1]], ds, {s: "And there is just no time. "}, 
		qs, {q: "Is there a lot of time?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[43,1]], ds, {s: "But I do not always get direct sun except in certain spots. "}, 
		qs, {q: "Is there direct sun everywhere?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[43,1]], ds, {s: "But I do not always get direct sun except in certain spots. "}, 
		qs, {q: "Is there direct sun everywhere?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[44,1]], ds, {s: "I am not sure all what we are going to have to do, whether we have three separate containers."}, 
		qs, {q: "Does somebody know what to do for sure?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[44,1]], ds, {s: "I am not sure all what we are going to have to do, whether we have three separate containers."}, 
		qs, {q: "Does somebody know what to do for sure?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[45,1]], ds, {s: "And you know how you put the headphones on and listen to it."}, 
		qs, {q: "Do you put on headphones to hear the music?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[45,1]], ds, {s: "And you know how you put the headphones on and listen to it."}, 
		qs, {q: "Do you put on headphones to hear the music?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[46,1]], ds, {s: "And it was really only acceptable if you were engaged and planning to get married in the relatively near future. "}],
	[["defaultStim",[46,2]], ds, {s: "And it was really only acceptable if you were engaged and planning to get married in the relatively near future. "}],
	[["defaultStim",[47,1]], ds, {s: "I was working in an office right after I got out of high school."}, 
		qs, {q: "Can people find work with only a high school degree?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[47,1]], ds, {s: "I was working in an office right after I got out of high school."}, 
		qs, {q: "Can people find work with only a high school degree?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[48,1]], ds, {s: "We, as I said, living in an area of Washington, D C. We definitely see this."}, 
		qs, {q: "Are there no residential areas in Washington D.C?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[48,1]], ds, {s: "We, as I said, living in an area of Washington, D C. We definitely see this."}, 
		qs, {q: "Are there no residential areas in Washington D.C?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[49,1]], ds, {s: "A judge, I think, would be the most appropriate person to be able to sentence somebody since they do it over and over again every day. "}, 
		qs, {q: "Is a judge a bad person to sentence someone?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[49,1]], ds, {s: "A judge, I think, would be the most appropriate person to be able to sentence somebody since they do it over and over again every day. "}, 
		qs, {q: "Is a judge a bad person to sentence someone?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[50,1]], ds, {s: "I don't know if I have been spoiled. "}],
	[["defaultStim",[50,2]], ds, {s: "I don't know if I have been spoiled. "}],
	[["defaultStim",[51,1]], ds, {s: "When I was getting robbed down in Florida, I was really considering electrifying doors, things like that like. "}, 
		qs, {q: "Are electrified doors options for preventing robberies?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[51,1]], ds, {s: "When I was getting robbed down in Florida, I was really considering electrifying doors, things like that like. "}, 
		qs, {q: "Are electrified doors options for preventing robberies?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[52,1]], ds, {s: "Anyone can go and vote. "}, 
		qs, {q: "Can everybody vote?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[52,1]], ds, {s: "Anyone can go and vote. "}, 
		qs, {q: "Can everybody vote?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[53,1]], ds, {s: "Well, I do not know how much you can learn. "}],
	[["defaultStim",[53,2]], ds, {s: "Well, I do not know how much you can learn. "}],
	[["defaultStim",[54,1]], ds, {s: "And my wife did this part. "}, 
		qs, {q: "Did the husband do everything?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[54,1]], ds, {s: "And my wife did this part. "}, 
		qs, {q: "Did the husband do everything?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[55,1]], ds, {s: "So it is boring. "}],
	[["defaultStim",[55,2]], ds, {s: "So it is boring. "}],
	[["StimZero.OriginalZero",[56,1]], ds, {s: "The day@NPHEAD1 it@RCSUBJ1 happens@RCVERB1 is ninety-eight percent of the planning usually."}],
	[["StimThat.OriginalZero",[56,2]], ds, {s: "The day@NPHEAD1 that@COMPL it@RCSUBJ1 happens@RCVERB1 is ninety-eight percent of the planning usually."}],
	[["StimThat.OriginalThat",[57,1]], ds, {s: "And when it is cold I am wearing sweatpants unless I am going to something special@NPHEAD1 that@COMPL my@RCSUBJ1 daughter@RCSUBJ2 is@RCVERB1 doing@RCVERB2 or something like that."}],
	[["StimZero.OriginalThat",[57,2]], ds, {s: "And when it is cold I am wearing sweatpants unless I am going to something special@NPHEAD1 my@RCSUBJ1 daughter@RCSUBJ2 is@RCVERB1 doing@RCVERB2 or something like that."}],
	[["StimThat.OriginalZero",[58,1]], ds, {s: "And there is only so much football@NPHEAD1 that@COMPL you@RCSUBJ1 can@RCVERB1 watch@RCVERB2."}],
	[["StimZero.OriginalZero",[58,2]], ds, {s: "And there is only so much football@NPHEAD1 you@RCSUBJ1 can@RCVERB1 watch@RCVERB2."}],
	[["StimZero.OriginalThat",[59,1]], ds, {s: "Well, most of what they are talking about in Washington is is the crime problems@NPHEAD1 they@RCSUBJ1 are@RCVERB1 having@RCVERB2 there."}, 
		qs, {q: "Are they ignoring the drug problem that they have in Washington D.C?" , hasCorrect: "No", randomOrder: false}],
	[["StimThat.OriginalThat",[59,1]], ds, {s: "Well, most of what they are talking about in Washington is is the crime problems@NPHEAD1 that@COMPL they@RCSUBJ1 are@RCVERB1 having@RCVERB2 there."}, 
		qs, {q: "Are they ignoring the drug problem that they have in Washington D.C?" , hasCorrect: "No", randomOrder: false}],
	[["StimZero.OriginalZero",[60,1]], ds, {s: "Hers was the first one@NPHEAD1 I@RCSUBJ1 got@RCVERB1."}],
	[["StimThat.OriginalZero",[60,2]], ds, {s: "Hers was the first one@NPHEAD1 that@COMPL I@RCSUBJ1 got@RCVERB1."}],
	[["StimThat.OriginalThat",[61,1]], ds, {s: "See I went out to Payless Cashways here a couple of days ago and got me one of those little can crushers@NPHEAD1 that@COMPL I@RCSUBJ1 could@RCVERB1 put@RCVERB2 on the wall."}],
	[["StimZero.OriginalThat",[61,2]], ds, {s: "See I went out to Payless Cashways here a couple of days ago and got me one of those little can crushers@NPHEAD1 I@RCSUBJ1 could@RCVERB1 put@RCVERB2 on the wall."}],
	[["StimThat.OriginalZero",[62,1]], ds, {s: "I can remember the first year@NPHEAD1 that@COMPL I@RCSUBJ1 moved@RCVERB1 here."}],
	[["StimZero.OriginalZero",[62,2]], ds, {s: "I can remember the first year@NPHEAD1 I@RCSUBJ1 moved@RCVERB1 here."}],
	[["StimZero.OriginalThat",[63,1]], ds, {s: "I have a few favorites@NPHEAD1 I@RCSUBJ1 use@RCVERB1 more than others."}],
	[["StimThat.OriginalThat",[63,2]], ds, {s: "I have a few favorites@NPHEAD1 that@COMPL I@RCSUBJ1 use@RCVERB1 more than others."}],
	[["StimZero.OriginalZero",[64,1]], ds, {s: "And it is everything@NPHEAD1 it@RCSUBJ1 is@RCVERB1 supposed@RCVERB2 to be."}, 
		qs, {q: "Is it living up to expectations?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimThat.OriginalZero",[64,1]], ds, {s: "And it is everything@NPHEAD1 that@COMPL it@RCSUBJ1 is@RCVERB1 supposed@RCVERB2 to be."}, 
		qs, {q: "Is it living up to expectations?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimThat.OriginalThat",[65,1]], ds, {s: "But it is not as many people@NPHEAD1 there that@COMPL I@RCSUBJ1 really enjoy@RCVERB1 seeing."}],
	[["StimZero.OriginalThat",[65,2]], ds, {s: "But it is not as many people@NPHEAD1 there I@RCSUBJ1 really enjoy@RCVERB1 seeing."}],
	[["StimThat.OriginalZero",[66,1]], ds, {s: "I mean I honestly do not really think I could have done much better than I did in the school@NPHEAD1 system@NPHEAD2 that@COMPL I@RCSUBJ1 was@RCVERB1 in@RCVERB2."}],
	[["StimZero.OriginalZero",[66,2]], ds, {s: "I mean I honestly do not really think I could have done much better than I did in the school@NPHEAD1 system@NPHEAD2 I@RCSUBJ1 was@RCVERB1 in@RCVERB2."}],
	[["StimZero.OriginalThat",[67,1]], ds, {s: "But the the ice storms really are stressful on all the plants@NPHEAD1 we@RCSUBJ1 have@RCVERB1 around."}, 
		qs, {q: "Are the ice storms nice to the plants that are around?" , hasCorrect: "No", randomOrder: false}],
	[["StimThat.OriginalThat",[67,1]], ds, {s: "But the the ice storms really are stressful on all the plants@NPHEAD1 that@COMPL we@RCSUBJ1 have@RCVERB1 around."}, 
		qs, {q: "Are the ice storms nice to the plants that are around?" , hasCorrect: "No", randomOrder: false}],
	[["StimZero.OriginalZero",[68,1]], ds, {s: "In the case@NPHEAD1 you@RCSUBJ1 were@RCVERB1 involved@RCVERB2 in@RCVERB3, you said it was just sort of a bank matter of some kind."}],
	[["StimThat.OriginalZero",[68,2]], ds, {s: "In the case@NPHEAD1 that@COMPL you@RCSUBJ1 were@RCVERB1 involved@RCVERB2 in@RCVERB3, you said it was just sort of a bank matter of some kind."}],
	[["StimThat.OriginalThat",[69,1]], ds, {s: "I have had two or three drug tests@NPHEAD1 that@COMPL I@RCSUBJ1 had@RCVERB1 to@RCVERB2 get@RCVERB3 before I could start working different jobs."}, 
		qs, {q: "Do some jobs require drug tests beforehand?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimZero.OriginalThat",[69,1]], ds, {s: "I have had two or three drug tests@NPHEAD1 I@RCSUBJ1 had@RCVERB1 to@RCVERB2 get@RCVERB3 before I could start working different jobs."}, 
		qs, {q: "Do some jobs require drug tests beforehand?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimThat.OriginalZero",[70,1]], ds, {s: "But it was cute, but not the biggest laugh@NPHEAD1 that@COMPL I@RCSUBJ1 have@RCVERB1 seen@RCVERB2."}],
	[["StimZero.OriginalZero",[70,2]], ds, {s: "But it was cute, but not the biggest laugh@NPHEAD1 I@RCSUBJ1 have@RCVERB1 seen@RCVERB2."}],
	[["StimZero.OriginalThat",[71,1]], ds, {s: "The U.S. is not the threat@NPHEAD1 we@RCSUBJ1 have@RCVERB1 made@RCVERB2 them out to be, even if they are saying that beneath the doors."}, 
		qs, {q: "Is the US the threat that they have been made out to be?" , hasCorrect: "No", randomOrder: false}],
	[["StimThat.OriginalThat",[71,1]], ds, {s: "The U.S. is not the threat@NPHEAD1 that@COMPL we@RCSUBJ1 have@RCVERB1 made@RCVERB2 them out to be, even if they are saying that beneath the doors."}, 
		qs, {q: "Is the US the threat that they have been made out to be?" , hasCorrect: "No", randomOrder: false}],
	[["StimZero.OriginalZero",[72,1]], ds, {s: "I think a lot of it is the families, the way@NPHEAD1 you@RCSUBJ1 were@RCVERB1 mentioning@RCVERB2."}],
	[["StimThat.OriginalZero",[72,2]], ds, {s: "I think a lot of it is the families, the way@NPHEAD1 that@COMPL you@RCSUBJ1 were@RCVERB1 mentioning@RCVERB2."}],
	[["StimThat.OriginalThat",[73,1]], ds, {s: "There is lots of things@NPHEAD1 that@COMPL we@RCSUBJ1 do@RCVERB1 not@RCVERB2 get@RCVERB3 told@RCVERB4 for good reason."}],
	[["StimZero.OriginalThat",[73,2]], ds, {s: "There is lots of things@NPHEAD1 we@RCSUBJ1 do@RCVERB1 not@RCVERB2 get@RCVERB3 told@RCVERB4 for good reason."}],
	[["StimThat.OriginalZero",[74,1]], ds, {s: "Actually yesterday I ended up talking to somebody else from the same lab@NPHEAD1 that@COMPL I@RCSUBJ1 am@RCVERB1 in@RCVERB2."}],
	[["StimZero.OriginalZero",[74,2]], ds, {s: "Actually yesterday I ended up talking to somebody else from the same lab@NPHEAD1 I@RCSUBJ1 am@RCVERB1 in@RCVERB2."}],
	[["StimZero.OriginalThat",[75,1]], ds, {s: "I think some of these people@NPHEAD1 they@RCSUBJ1 claim@RCVERB1 as middle eastern experts do not have a clue sometimes."}, 
		qs, {q: "Are all the people that are claimed as Middle East experts very knowledgable?" , hasCorrect: "No", randomOrder: false}],
	[["StimThat.OriginalThat",[75,1]], ds, {s: "I think some of these people@NPHEAD1 that@COMPL they@RCSUBJ1 claim@RCVERB1 as middle eastern experts do not have a clue sometimes."}, 
		qs, {q: "Are all the people that are claimed as Middle East experts very knowledgable?" , hasCorrect: "No", randomOrder: false}],
	[["StimZero.OriginalZero",[76,1]], ds, {s: "She is up in the house and talked to my mother the whole time@NPHEAD1 we@RCSUBJ1 were@RCVERB1 out@RCVERB2 hunting and stuff."}],
	[["StimThat.OriginalZero",[76,2]], ds, {s: "She is up in the house and talked to my mother the whole time@NPHEAD1 that@COMPL we@RCSUBJ1 were@RCVERB1 out@RCVERB2 hunting and stuff."}],
	[["StimThat.OriginalThat",[77,1]], ds, {s: "And as far as them entertaining the rights@NPHEAD1 that@COMPL they@RCSUBJ1 should@RCVERB1 have@RCVERB2."}],
	[["StimZero.OriginalThat",[77,2]], ds, {s: "And as far as them entertaining the rights@NPHEAD1 they@RCSUBJ1 should@RCVERB1 have@RCVERB2."}],
	[["StimThat.OriginalZero",[78,1]], ds, {s: "Because if we do not want that to happen, all@NPHEAD1 that@COMPL we@RCSUBJ1 have@RCVERB1 to@RCVERB2 do@RCVERB3 is just call the phone company and say look, I want my name unlisted."}, 
		qs, {q: "Is is true that to get more privacy all that you have to do is call up the phone company and become unlisted?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimZero.OriginalZero",[78,1]], ds, {s: "Because if we do not want that to happen, all@NPHEAD1 we@RCSUBJ1 have@RCVERB1 to@RCVERB2 do@RCVERB3 is just call the phone company and say look, I want my name unlisted."}, 
		qs, {q: "Is is true that to get more privacy all that you have to do is call up the phone company and become unlisted?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimZero.OriginalThat",[79,1]], ds, {s: "They convicted him of a robbery@NPHEAD1 he@RCSUBJ1 could@RCVERB1 not@RCVERB2 physically@RCVERB3 have@RCVERB4 been@RCVERB5 able@RCVERB6 to@RCVERB7 commit@RCVERB8."}],
	[["StimThat.OriginalThat",[79,2]], ds, {s: "They convicted him of a robbery@NPHEAD1 that@COMPL he@RCSUBJ1 could@RCVERB1 not@RCVERB2 physically@RCVERB3 have@RCVERB4 been@RCVERB5 able@RCVERB6 to@RCVERB7 commit@RCVERB8."}],
	[["StimZero.OriginalZero",[80,1]], ds, {s: "She told me some of the things@NPHEAD1 you@RCSUBJ1 can@RCVERB1 do@RCVERB2."}],
	[["StimThat.OriginalZero",[80,2]], ds, {s: "She told me some of the things@NPHEAD1 that@COMPL you@RCSUBJ1 can@RCVERB1 do@RCVERB2."}],
	[["StimThat.OriginalThat",[81,1]], ds, {s: "All of her animals@NPHEAD1 that@COMPL she@RCSUBJ1 ever had@RCVERB1 were adopted."}, 
		qs, {q: "Did she adopt all the animals she owned?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimZero.OriginalThat",[81,1]], ds, {s: "All of her animals@NPHEAD1 she@RCSUBJ1 ever had@RCVERB1 were adopted."}, 
		qs, {q: "Did she adopt all the animals she owned?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimThat.OriginalZero",[82,1]], ds, {s: "Al Jarreau, he is somebody@NPHEAD1 that@COMPL I@RCSUBJ1 like@RCVERB1."}, 
		qs, {q: "Is Al Jarreau a man that is disliked by this person?" , hasCorrect: "No", randomOrder: false}],
	[["StimZero.OriginalZero",[82,1]], ds, {s: "Al Jarreau, he is somebody@NPHEAD1 I@RCSUBJ1 like@RCVERB1."}, 
		qs, {q: "Is Al Jarreau a man that is disliked by this person?" , hasCorrect: "No", randomOrder: false}],
	[["StimZero.OriginalThat",[83,1]], ds, {s: "And the rates@NPHEAD1 we@RCSUBJ1 keep@RCVERB1 paying@RCVERB2 seem to keep increasing."}, 
		qs, {q: "Do the rates keep going up?" , hasCorrect: "Yes", randomOrder: false}],
	[["StimThat.OriginalThat",[83,1]], ds, {s: "And the rates@NPHEAD1 that@COMPL we@RCSUBJ1 keep@RCVERB1 paying@RCVERB2 seem to keep increasing."}, 
		qs, {q: "Do the rates keep going up?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[84,1]], ds, {s: "I am just going to have to put it in the car sometimes and listen to it. "}],
	[["defaultStim",[84,2]], ds, {s: "I am just going to have to put it in the car sometimes and listen to it. "}],
	[["defaultStim",[85,1]], ds, {s: "And I have watched Gross Anatomy. "}, 
		qs, {q: "Is it possible to watch Gross Anatomy?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[85,1]], ds, {s: "And I have watched Gross Anatomy. "}, 
		qs, {q: "Is it possible to watch Gross Anatomy?" , hasCorrect: "Yes", randomOrder: false}],
	[["defaultStim",[86,1]], ds, {s: "But they are so expensive. "}, 
		qs, {q: "Are  they cheap?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[86,1]], ds, {s: "But they are so expensive. "}, 
		qs, {q: "Are  they cheap?" , hasCorrect: "No", randomOrder: false}],
	[["defaultStim",[87,1]], ds, {s: "She knows how to twist this around."}],
	[["defaultStim",[87,2]], ds, {s: "She knows how to twist this around."}],
	["contact", "Message", {consentRequired: false, html: {include: "contacts.html"}}],
    ["cond", "Message", {consentRequired: false, html: {include: "code.html"}}]
];

