var shuffleSequence = seq("intro", "info", "startprac", "practice", "endprac", sepWith("sep", anyOf("filler", startsWith("StimZero"), startsWith("StimThat"))), "contact", "sr", "code");

var pastworkers = ["A18C1OETHYLHZY", "A1CX0MFDJHAJPG", "A1RWNYJA5X25YH", "A1WK525EJS3SYA", "A1X8IL45JKM9TF", "A253Q11TZPQPIZ", "A2FJUD15XITAOC", "A2HM35CWB7IIFM", "A2LO9Y9SJHXPR", "A2RP4Y1BDU8F8A", "A30JQZFOA435PX", "A31WOUTVXO1VE4", "A31Z06KS8M1B88", "A363H2EKG4U5IJ", "A3KFA3FHL8F89R", "A3O749MMVC22QA", "A3OT61DL0DY283", "A3SWH7DHWHP0BO", "A3TK9CLBA65ZZE", "A3ULQTETISV24Z", "A3UWBL2XG38CO8", "A3VQYU541S4RDA", "A44LL84B4CKIK", "A98XHW6B1VSSQ"];

var ds = "RegionedSentence";
var qs = "Question";

var manualSendResults = true;

var defaults = [
    "Separator", {
        transfer: 1500,
        normalMessage: "Please wait for the next sentence",
        errorMessage: "Wrong. Please wait for the next sentence" },
    "RegionedSentence", {
        mode: "self-paced reading" },
    "Question", {
        as: ["Yes","No"],
        randomOrder: false,
        hasCorrect: true }
];

var items = [
    ["sr", "__SendResults__", { }],
    ["sep", "Separator", {}],
    ["intro", "Message", {consentRequired: true, html: {include: "intro.html"}}],
	["info", "Form", {
        html: {include: "info.html"},
        validators: {
            workerid: function(s) {if (pastworkers.indexOf(s) == -1) return true; else return "You have already done an RC SPR experiment";}
        }
    }],
    ["startprac", "Message", {consentRequired: false, html: {include: "start_practice.html"}}],
    ["practice", ds, {s: "She knows how to twist this around."}],
    ["practice", ds, {s: "But they're so expensive."}, 
        qs, {q: "Are  they cheap?" , hasCorrect: "No", randomOrder: false}],
    ["practice", ds, {s: "I'm just going to have to put it, in the car sometimes and listen to it."}],
    ["practice", ds, {s: "And I have watched, uh, Gross Anatomy."}, 
        qs, {q: "Is it possible to watch Gross Anatomy?" , hasCorrect: "Yes", randomOrder: false}],
    ["endprac", "Message", {consentRequired: false, html: {include: "end_practice.html"}}],
    [["filler", 6], ds, {s: "But all of a sudden it just wasn't working."}],
    [["StimZero.OriginalZero", 7], ds, {s: "So the day@NPHEAD1 it@RCSUBJ1 happens@RCVERB1 is ninety-eight percent of the planning usually."}],
    [["StimThat.OriginalZero", 7], ds, {s: "So the day@NPHEAD1 that@COMPL it@RCSUBJ1 happens@RCVERB1 is ninety-eight percent of the planning usually."}],
    [["filler", 8], ds, {s: "It was, it was really amazing."}],
    [["filler", 9], ds, {s: "Now we can put all our yard clippings out."}, 
        qs, {q: "Do the yard clippings go out?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalThat",[10,7]], ds, {s: "And when it's cold I'm wearing sweatpants unless I'm going to something special@NPHEAD1 that@COMPL my@RCSUBJ1 daughter's@RCSUBJ2 doing@RCVERB1 or something like that."}],
    [["StimZero.OriginalThat",[10,7]], ds, {s: "And when it's cold I'm wearing sweatpants unless I'm going to something special@NPHEAD1 my@RCSUBJ1 daughter's@RCSUBJ2 doing@RCVERB1 or something like that."}],
    [["filler", 11], ds, {s: "With all of you living so close together."}],
    [["filler", 12], ds, {s: "You clip recipes."}, 
        qs, {q: "Can recipes be clipped?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalZero",[13,7]], ds, {s: "And there's only so much football@NPHEAD1 that@COMPL you@RCSUBJ1 can@RCVERB1 watch.@RCVERB2"}],
    [["StimZero.OriginalZero",[13,7]], ds, {s: "And there's only so much football@NPHEAD1 you@RCSUBJ1 can@RCVERB1 watch.@RCVERB2"}],
    [["filler", 14], ds, {s: "Well I know how you feel."}],
    [["filler", 15], ds, {s: "And that was pretty scandalous."}],
    [["StimZero.OriginalThat",[16,7]], ds, {s: "Well, most of what they're talking about in Washington is is the crime problems@NPHEAD1 they're@RCSUBJ1 having@RCVERB1 there."}, 
        qs, {q: "Are they ignoring the drug problem that they have in Washington D.C?" , hasCorrect: "No", randomOrder: false}],
    [["StimThat.OriginalThat",[16,7]], ds, {s: "Well, most of what they're talking about in Washington is is the crime problems@NPHEAD1 that@COMPL they're@RCSUBJ1 having@RCVERB1 there."}, 
        qs, {q: "Are they ignoring the drug problem that they have in Washington D.C?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 17], ds, {s: "And you know how you put the headphones on and listen to it."}, 
        qs, {q: "Do you put on headphones to hear the music?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 18], ds, {s: "So it was like I had to go all the way back to the main drain and start all over."}, 
        qs, {q: "Was it necessary to start over again?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimZero.OriginalZero",[19,7]], ds, {s: "So hers was the first one@NPHEAD1 I@RCSUBJ1 got.@RCVERB1"}],
    [["StimThat.OriginalZero",[19,7]], ds, {s: "So hers was the first one@NPHEAD1 that@COMPL I@RCSUBJ1 got.@RCVERB1"}],
    [["filler", 20], ds, {s: "Two ways was seventy miles."}, 
        qs, {q: "Was it a seventy mile travel for two ways?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 21], ds, {s: "That's always good."}],
    [["StimThat.OriginalThat",[22,7]], ds, {s: "See I went out to Payless Cashways here a couple of days ago as a matter of fact and got me one of those little can crushers@NPHEAD1 that@COMPL I@RCSUBJ1 could@RCVERB1 put@RCVERB2 on the wall."}],
    [["StimZero.OriginalThat",[22,7]], ds, {s: "See I went out to Payless Cashways here a couple of days ago as a matter of fact and got me one of those little can crushers@NPHEAD1 I@RCSUBJ1 could@RCVERB1 put@RCVERB2 on the wall."}],
    [["filler", 23], ds, {s: "But I don't always get direct sun except in certain spots."}, 
        qs, {q: "Is there direct sun everywhere?" , hasCorrect: "No", randomOrder: false}],
    [["StimThat.OriginalZero",[24,7]], ds, {s: "I can remember the first year@NPHEAD1 that@COMPL I@RCSUBJ1 moved@RCVERB1 here."}],
    [["StimZero.OriginalZero",[24,7]], ds, {s: "I can remember the first year@NPHEAD1 I@RCSUBJ1 moved@RCVERB1 here."}],
    [["filler", 25], ds, {s: "And when you're writing up budgets, you wonder, okay, how much money do we need?"}, 
        qs, {q: "When writing budgets, is the amount of money needed already known? " , hasCorrect: "No", randomOrder: false}],
    [["filler", 26], ds, {s: "Ours is, uh, on the small end."}],
    [["filler", 27], ds, {s: "I hope I don't see a lot more single moms."}, 
        qs, {q: "Is the abundance of single moms a good sign?" , hasCorrect: "No", randomOrder: false}],
    [["StimZero.OriginalThat",[28,7]], ds, {s: "I have a few favorites@NPHEAD1 I@RCSUBJ1 use@RCVERB1 more than others."}],
    [["StimThat.OriginalThat",[28,7]], ds, {s: "I have a few favorites@NPHEAD1 that@COMPL I@RCSUBJ1 use@RCVERB1 more than others."}],
    [["filler", 29], ds, {s: "And it's so easy."}],
    [["filler", 30], ds, {s: "We, um, as I said, living in an area of Washington,_D.C., we definitely see this."}, 
        qs, {q: "Are there no residential areas in Washington, D.C.?" , hasCorrect: "No", randomOrder: false}],
    [["StimZero.OriginalZero",[31,7]], ds, {s: "And it's, it's everything@NPHEAD1 it's@RCSUBJ1 supposed@RCVERB1 to be."}, 
        qs, {q: "Is it living up to expectations?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalZero",[31,7]], ds, {s: "And it's, it's everything@NPHEAD1 that@COMPL it's@RCSUBJ1 supposed@RCVERB1 to be."}, 
        qs, {q: "Is it living up to expectations?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 32], ds, {s: "I was working in Cameroon, Africa."}, 
        qs, {q: "Is Cameroon in Africa?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 33], ds, {s: "But, we pra-, we went that way."}],
    [["filler", 34], ds, {s: "And then he just started doing it."}],
    [["StimThat.OriginalThat",[35,7]], ds, {s: "But it's not as many people@NPHEAD1 there that@COMPL I@RCSUBJ1 really, really enjoy@RCVERB1 seeing."}],
    [["StimZero.OriginalThat",[35,7]], ds, {s: "But it's not as many people@NPHEAD1 there I@RCSUBJ1 really, really enjoy@RCVERB1 seeing."}],
    [["filler", 36], ds, {s: "They would have collapsed."}],
    [["filler", 37], ds, {s: "When I was getting robbed down in Florida, I was really considering electrifying doors um, things like that like."}, 
        qs, {q: "Are electrified doors options for preventing robberies?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalZero",[38,7]], ds, {s: "I mean I don't, I honestly don't really think I could have, you know, done much better than I did in the school@NPHEAD1 system@NPHEAD2 that@COMPL I@RCSUBJ1 was@RCVERB1 in.@RCVERB2"}],
    [["StimZero.OriginalZero",[38,7]], ds, {s: "I mean I don't, I honestly don't really think I could have, you know, done much better than I did in the school@NPHEAD1 system@NPHEAD2 I@RCSUBJ1 was@RCVERB1 in.@RCVERB2"}],
    [["filler", 39], ds, {s: "Well, I don't know how much you can learn."}],
    [["filler", 40], ds, {s: "So we, we still feel very new."}],
    [["StimZero.OriginalThat",[41,7]], ds, {s: "But the the ice storms really are stressful on all the plants@NPHEAD1 we@RCSUBJ1 have@RCVERB1 around."}, 
        qs, {q: "Are the ice storms nice to the plants that are around?" , hasCorrect: "No", randomOrder: false}],
    [["StimThat.OriginalThat",[41,7]], ds, {s: "But the the ice storms really are stressful on all the plants@NPHEAD1 that@COMPL we@RCSUBJ1 have@RCVERB1 around."}, 
        qs, {q: "Are the ice storms nice to the plants that are around?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 42], ds, {s: "Oh, in the oil business."}],
    [["filler", 43], ds, {s: "And there's just no time."}, 
        qs, {q: "Is there a lot of time?" , hasCorrect: "No", randomOrder: false}],
    [["StimThat.OriginalThat",[44,7]], ds, {s: "I had, I've had two or three drug tests@NPHEAD1 that@COMPL I@RCSUBJ1 had@RCVERB1 to@RCVERB2 get@RCVERB3 before I could start working at a job, different jobs."}, 
        qs, {q: "Do some jobs require drug tests beforehand?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimZero.OriginalThat",[44,7]], ds, {s: "I had, I've had two or three drug tests@NPHEAD1 I@RCSUBJ1 had@RCVERB1 to@RCVERB2 get@RCVERB3 before I could start working at a job, different jobs."}, 
        qs, {q: "Do some jobs require drug tests beforehand?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 45], ds, {s: "Maybe it isn't drywall."}],
    [["StimZero.OriginalZero",[46,7]], ds, {s: "In the case@NPHEAD1 you@RCSUBJ1 were@RCVERB1 involved@RCVERB2 in@RCVERB3, you said it was just sort of a bank matter of some kind."}],
    [["StimThat.OriginalZero",[46,7]], ds, {s: "In the case@NPHEAD1 that@COMPL you@RCSUBJ1 were@RCVERB1 involved@RCVERB2 in@RCVERB3, you said it was just sort of a bank matter of some kind."}],
    [["filler", 47], ds, {s: "Anyone can go and vote."}, 
        qs, {q: "Can everybody vote?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 48], ds, {s: "I could easily envision that."}],
    [["StimThat.OriginalZero",[49,7]], ds, {s: "But it was, I mean, it was, it was cute, but not the biggest laugh@NPHEAD1 that@COMPL I've@RCSUBJ1 seen.@RCVERB1"}],
    [["StimZero.OriginalZero",[49,7]], ds, {s: "But it was, I mean, it was, it was cute, but not the biggest laugh@NPHEAD1 I've@RCSUBJ1 seen.@RCVERB1"}],
    [["filler", 50], ds, {s: "And then they said okay, no."}],
    [["StimZero.OriginalThat",[51,7]], ds, {s: "The U.S.isn't the threat@NPHEAD1 we've@RCSUBJ1 always made@RCVERB1 them out to be, you know, even if they're saying that beneath the doors."}, 
        qs, {q: "Is the US the threat that they have been made out to be?" , hasCorrect: "No", randomOrder: false}],
    [["StimThat.OriginalThat",[51,7]], ds, {s: "The U.S.isn't the threat@NPHEAD1 that@COMPL we've@RCSUBJ1 always made@RCVERB1 them out to be, you know, even if they're saying that beneath the doors."}, 
        qs, {q: "Is the US the threat that they have been made out to be?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 52], ds, {s: "I mean, he's, he's gotten out."}],
    [["filler", 53], ds, {s: "Maybe this pre-group of people could decide, you know, which kind of, uh, you know, where they could go from there."}, 
        qs, {q: "Should the pre-group of people fly somewhere?" , hasCorrect: "No", randomOrder: false}],
    [["StimZero.OriginalZero",[54,7]], ds, {s: "I think a lot of it is the families, the way@NPHEAD1 you@RCSUBJ1 were@RCVERB1 mentioning.@RCVERB2"}],
    [["StimThat.OriginalZero",[54,7]], ds, {s: "I think a lot of it is the families, the way@NPHEAD1 that@COMPL you@RCSUBJ1 were@RCVERB1 mentioning.@RCVERB2"}],
    [["filler", 55], ds, {s: "We have very windy winters and very cold."}, 
        qs, {q: "Are the winters warm?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 56], ds, {s: "But you actually hand quilted it yourself."}, 
        qs, {q: "Is it possible to quilt by hand?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalZero",[57,7]], ds, {s: "Actually, yesterday I ended up talking to somebody else from the same lab@NPHEAD1 that@COMPL I'm@RCSUBJ1 in.@RCVERB1"}],
    [["StimZero.OriginalZero",[57,7]], ds, {s: "Actually, yesterday I ended up talking to somebody else from the same lab@NPHEAD1 I'm@RCSUBJ1 in.@RCVERB1"}],
    [["filler", 58], ds, {s: "Well, my wife's from Galveston."}],
    [["filler", 59], ds, {s: "Well, it was nice talking to you."}],
    [["StimThat.OriginalThat",[60,7]], ds, {s: "There's lots of things@NPHEAD1 that@COMPL we@RCSUBJ1 don't@RCVERB1 get@RCVERB2 told@RCVERB3 for good reason."}],
    [["StimZero.OriginalThat",[60,7]], ds, {s: "There's lots of things@NPHEAD1 we@RCSUBJ1 don't@RCVERB1 get@RCVERB2 told@RCVERB3 for good reason."}],
    [["filler", 61], ds, {s: "We have a set amount."}, 
        qs, {q: "Is there a variable amount?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 62], ds, {s: "I do, uh, I do the easy stuff now."}],
    [["StimZero.OriginalZero",[63,7]], ds, {s: "She's up in the house and talked to my mother the whole time@NPHEAD1 we@RCSUBJ1 were@RCVERB1 out@RCVERB2 hunting and stuff."}],
    [["StimThat.OriginalZero",[63,7]], ds, {s: "She's up in the house and talked to my mother the whole time@NPHEAD1 that@COMPL we@RCSUBJ1 were@RCVERB1 out@RCVERB2 hunting and stuff."}],
    [["filler", 64], ds, {s: "Uh, so that, uh, a judge, I think, would be the most appropriate person to, uh, to be able to sentence somebody since they do it over and over again every day."}, 
        qs, {q: "Is a judge a bad person to sentence someone?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 65], ds, {s: "So I mean, it's boring."}],
    [["StimThat.OriginalThat",[66,7]], ds, {s: "And as far as, like, them entertaining the rights@NPHEAD1 that@COMPL they@RCSUBJ1 should@RCVERB1 have.@RCVERB2"}],
    [["StimZero.OriginalThat",[66,7]], ds, {s: "And as far as, like, them entertaining the rights@NPHEAD1 they@RCSUBJ1 should@RCVERB1 have.@RCVERB2"}],
    [["filler", 67], ds, {s: "Um, I work in the computer lab at school."}, 
        qs, {q: "Are there computer labs in some schools?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 68], ds, {s: "I don't know if I've been spoiled."}],
    [["StimZero.OriginalThat",[69,7]], ds, {s: "I, I think some of these people@NPHEAD1 they@RCSUBJ1 claim@RCVERB1 as middle eastern experts don't, don't have a clue sometimes."}, 
        qs, {q: "Are all the people that are claimed as Middle East experts very knowledgable?" , hasCorrect: "No", randomOrder: false}],
    [["StimThat.OriginalThat",[69,7]], ds, {s: "I, I think some of these people@NPHEAD1 that@COMPL they@RCSUBJ1 claim@RCVERB1 as middle eastern experts don't, don't have a clue sometimes."}, 
        qs, {q: "Are all the people that are claimed as Middle East experts very knowledgable?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 70], ds, {s: "And, my wife did this part."}, 
        qs, {q: "Did the husband do everything?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 71], ds, {s: "There's, um, a thing called Pfeiffer Rim."}, 
        qs, {q: "Is there something called Pfeiffer Rim?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalZero",[72,7]], ds, {s: "Because, you know, if we don't want that to happen, all@NPHEAD1 that@COMPL we@RCSUBJ1 have@RCVERB1 to@RCVERB2 do@RCVERB3 is just call the phone company and say look, you know, I want my name unlisted, or want my, you know."}, 
        qs, {q: "Is is true that to get more privacy all that you have to do is call up the phone company and become unlisted?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimZero.OriginalZero",[72,7]], ds, {s: "Because, you know, if we don't want that to happen, all@NPHEAD1 we@RCSUBJ1 have@RCVERB1 to@RCVERB2 do@RCVERB3 is just call the phone company and say look, you know, I want my name unlisted, or want my, you know."}, 
        qs, {q: "Is is true that to get more privacy all that you have to do is call up the phone company and become unlisted?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 73], ds, {s: "And it was really only, uh, acceptable if you were engaged and planning to get married in, in the relatively near future."}],
    [["filler", 74], ds, {s: "Well, they started out really bad."}, 
        qs, {q: "Did they start out really bad?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 75], ds, {s: "Well, they're dangerous."}],
    [["StimZero.OriginalThat",[76,7]], ds, {s: "They convicted him of a robbery@NPHEAD1 he@RCSUBJ1 could@RCVERB1 not@RCVERB2 physically@RCVERB3 have@RCVERB4 been@RCVERB5 able@RCVERB6 to@RCVERB7 commit.@RCVERB8"}],
    [["StimThat.OriginalThat",[76,7]], ds, {s: "They convicted him of a robbery@NPHEAD1 that@COMPL he@RCSUBJ1 could@RCVERB1 not@RCVERB2 physically@RCVERB3 have@RCVERB4 been@RCVERB5 able@RCVERB6 to@RCVERB7 commit.@RCVERB8"}],
    [["filler", 77], ds, {s: "But I'm trying to workup to three miles."}],
    [["filler", 78], ds, {s: "I was working in an office, right after I got out of high school."}, 
        qs, {q: "Can people find work with only a high school degree?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalThat",[79,7]], ds, {s: "All of her animals@NPHEAD1 that@COMPL she@RCSUBJ1 ever had@RCVERB1 were adopted."}, 
        qs, {q: "Did she adopt all the animals she owned?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimZero.OriginalThat",[79,7]], ds, {s: "All of her animals@NPHEAD1 she@RCSUBJ1 ever had@RCVERB1 were adopted."}, 
        qs, {q: "Did she adopt all the animals she owned?" , hasCorrect: "Yes", randomOrder: false}],
    [["filler", 80], ds, {s: "Um, we're late twenties."}],
    [["filler", 81], ds, {s: "We kind of give her the third degree."}],
    [["StimZero.OriginalZero",[82,7]], ds, {s: "She told me some of the things@NPHEAD1 you@RCSUBJ1 can@RCVERB1 do.@RCVERB2"}],
    [["StimThat.OriginalZero",[82,7]], ds, {s: "She told me some of the things@NPHEAD1 that@COMPL you@RCSUBJ1 can@RCVERB1 do.@RCVERB2"}],
    [["filler", 83], ds, {s: "Recycled paper is actually very expensive."}, 
        qs, {q: "Is recycled paper cheap?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 84], ds, {s: "Oh, wouldn't it, wouldn't it though."}],
    [["StimThat.OriginalZero",[85,7]], ds, {s: "Al Jarreau, he's somebody@NPHEAD1 that@COMPL I@RCSUBJ1 like.@RCVERB1"}, 
        qs, {q: "Is Al Jarreau a man that is disliked by this person?" , hasCorrect: "No", randomOrder: false}],
    [["StimZero.OriginalZero",[85,7]], ds, {s: "Al Jarreau, he's somebody@NPHEAD1 I@RCSUBJ1 like.@RCVERB1"}, 
        qs, {q: "Is Al Jarreau a man that is disliked by this person?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 86], ds, {s: "I'm not sure all what we're going to have to do, whether we have three separate containers."}, 
        qs, {q: "Does somebody know what to do for sure?" , hasCorrect: "No", randomOrder: false}],
    [["filler", 87], ds, {s: "But I've been unable to do that, because I hurt my foot about five years ago."}, 
        qs, {q: "Can all activities be done with a hurt foot?" , hasCorrect: "No", randomOrder: false}],
    [["StimZero.OriginalThat",[88,7]], ds, {s: "And the rates@NPHEAD1 we@RCSUBJ1 keep@RCVERB1 paying@RCVERB2 seem to keep increasing, you know."}, 
        qs, {q: "Do the rates keep going up?" , hasCorrect: "Yes", randomOrder: false}],
    [["StimThat.OriginalThat",[88,7]], ds, {s: "And the rates@NPHEAD1 that@COMPL we@RCSUBJ1 keep@RCVERB1 paying@RCVERB2 seem to keep increasing, you know."}, 
        qs, {q: "Do the rates keep going up?" , hasCorrect: "Yes", randomOrder: false}],
    ["contact", "Message", {consentRequired: false, html: {include: "contacts.html"}}],
    ["code", "Message", {consentRequired: false, html: {include: "code.html"}}]
];

